services:
  nginx:
    image: nginx:stable-alpine3.17-slim
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/api/static
    networks:
      - chacrm2-net
  app:
    #image: registry.int.janelia.org/janeliascicomp/chacrm2
    build: ./api
    restart: unless-stopped
    volumes:
        - ./api:/api
        - static_volume:/api/static
    environment:
      - PYTHONUNBUFFERED=1
      - CONFIG_SERVER_URL=https://config.int.janelia.org/
    networks:
        - chacrm2-net
    ports:
      - 81:8000

networks:
  chacrm2-net:
      driver: bridge

volumes:
  static_volume:
